### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by peter279k** [drewjoh/phpPayPal#16]
As title, I wonder know this project status.

Some issues and PRs need to be reviewed, concerned and merged.

@drewjoh, could you concern this issue if possible at your available time? Thanks.

**Comment by drewjoh** [comment]
This project is more than 6 years since the last update.  There are numerous other, new and updated PayPal libraries I would think.  :)

For this project, I no longer maintain it.  

Many have forked it and used what they can.  :)

Best of luck!
