### ISSUE TITLE
format_response() needs type differentiation

### ISSUE THREAD

**Issue by jdinse** [drewjoh/phpPayPal#8]
Hi!

Recently, I saw that format_response() always copies the variables which are given for a 'DoReferenceTransaction' response and doesn't make any differences of the response type. So format_response() should have a parameter $type like generateNVPString().

However, thanks for the nice work! Very helpful!

**Comment by drewjoh** [comment]
Thank jdinse!  Just came across this in having to reuse my class in a new project and I'm not sure how this wasn't noticed sooner! :+1:
